epochs_mapper = {
    "action_recognition": "train.num_epochs",
    "analytics": "",
    "annotations": "",
    "augmentation": "",
    "auto_label": "",
    "classification_pyt": "train.train_config.runner.max_epochs",
    "classification_tf2": "train.num_epochs",
    "deformable_detr": "train.num_epochs",
    "detectnet_v2": "training_config.num_epochs",
    "dino": "train.num_epochs",
    "efficientdet_tf2": "train.num_epochs",
    "mal": "train.num_epochs",
    "ml_recog": "train.num_epochs",
    "ocdnet": "train.num_epochs",
    "ocrnet": "train.num_epochs",
    "optical_inspection": "train.num_epochs",
    "pointpillars": "train.num_epochs",
    "pose_classification": "train.num_epochs",
    "re_identification": "train.num_epochs",
    "segformer": "train.max_iters",
    "unet": "training_config.epochs",
}

backbone_mapper = {
    "action_recognition": "model.backbone",
    "analytics": "",
    "annotations": "",
    "augmentation": "",
    "auto_label": "",
    "classification_pyt": "model.backbone.type",
    "classification_tf2": "model.backbone",
    "deformable_detr": "model.backbone",
    "detectnet_v2": "model_config.arch",
    "dino": "model.backbone",
    "efficientdet_tf2": "model.name",
    "mal": "model.arch",
    "ml_recog": "model.backbone",
    "ocdnet": "model.backbone",
    "ocrnet": "model.backbone",
    "optical_inspection": "model.backbone",
    "pointpillars": "model.backbone_2d.name",
    "pose_classification": "",
    "re_identification": "model.backbone",
    "segformer": "model.backbone.type",
    "unet": "model_config.arch",
}

image_size_mapper = {
    "action_recognition": "model.input_height,model.input_width",
    "analytics": "",
    "annotations": "",
    "augmentation": "",
    "auto_label": "",
    "classification_pyt": "",
    "classification_tf2": "model.input_height,model.input_width",
    "deformable_detr": "",
    "detectnet_v2": "augmentation_config.preprocessing.output_image_height,augmentation_config.preprocessing.output_image_width",
    "dino": "",
    "efficientdet_tf2": "model.input_height,model.input_width",
    "mal": "",
    "ml_recog": "model.input_height,model.input_width",
    "ocdnet": "",
    "ocrnet": "model.input_height,model.input_width",
    "optical_inspection": "dataset.image_height,dataset.image_width",
    "pointpillars": "",
    "pose_classification": "",
    "re_identification": "model.input_height,model.input_width",
    "segformer": "model.input_height,model.input_width",
    "unet": "model_config.model_input_height,model_config.model_input_width",
}

# Include your network if it has spec fields to load full network as PTM and loading backbone portion alone
ptm_mapper = {
    "backbone": {
        "classification_pyt": "model.backbone.pretrained",
        "dino": "model.pretrained_backbone_path",
    },
    "end_to_end": {
        "classification_pyt": "model.init_cfg.checkpoint",
        "dino": "train.pretrained_model_path",
    }
}
